export enum TipoTransaccion {
    CONSULTA = "CONSULTA",
    DEPOSITO = "DEPOSITO",
    RETIRO = "RETIRO",
    TRANSFERENCIA = "TRANSFERENCIA",
    TRANSFERENCIA_INTERNA = "TRANSFERENCIA_INTERNA",
    TRANSFERENCIA_INTERBANCARIA = "TRANSFERENCIA_INTERBANCARIA"
}